### ISSUE TITLE
inserting every fontUsage (including unused font) for multiple html target

### ISSUE THREAD

**Issue by palindrom615** [Munter/subfont#80] opened 2020-02-29 10:32 UTC
## as-is

* `first.html` uses `font1` for unicode range U+0 ~ 10.

* `second.html` uses `font1` for unicode range U+10 ~ 20  and `font2` for unicode range U+100 ~ 200.

```
subfont -i --no-fallbacks first.html second.html
```

If I do right, the command above makes the result:

* inserts `first.html` `font1__subset` which contains unicode range U+0 ~ 20
* inserts `second.html` `font1__subset` which contains unicode range U+0 ~ 20 **and** `font2__subet` contains unicode U+100 ~ 200

## to-be

If `subsetPerPage` option is not `true`, isn't it right to also insert `font2__subset` in `first.html`?

because, subsetting multiple html target without `subsetPerPage` option should include **union** of glyphs in every html files.

## my use case

I am using subfont for my gatsby site without `fallbacks` option. If I enter the site from `/first` and try to move on `/second` which contains `font2` which is not used in `/first`, the font is broken because of the issue above. (FYI: If you don't know react SSR,  when I cross a link in rehydrated(fully loaded) react app it does not load new html but uses original html and render contents with javascript.)

**Comment by papandreou** [comment] 2020-07-11 15:27
The current behavior is by design. In a "normal" setup where moving from `first.html` to `second.html` involves an actual page navigation, it would be wasteful to include all the subsets that aren't used on the individual page. (Well, maybe it wouldn't be super wasteful to just include the `@font-face` declarations for the other subsets, but it would certainly be bad to preload them).

I understand your use case and wouldn't be opposed to a new mode that's better suited for this sort of application. But I don't think it should be an implicit result of not passing `--subset-per-page`. Maybe we could add another switch, or turn `--subset-per-page` into a switch with 3 possible values?

What do you think, @Munter?

**Comment by papandreou** [comment] 2020-07-12 11:08
We could also consider removing support for the `subsetPerPage: false` mode as it's not that useful (and can be emulated by running subfont multiple times).

**Comment by papandreou** [comment] 2020-07-12 11:37
I made some test cases for how that "ssr" mode could work: https://github.com/Munter/subfont/pull/111

**Comment by Munter** [comment] 2020-07-12 13:13
The `subsetPerPage` does indeed not seem super useful. We probably went overboard with that one "because we could".

I like the idea of injecting unused declarations without preloading them, and I could see that option make sense for these server-rendered with client hydration/routing setups.

**Comment by papandreou** [comment] 2020-07-12 13:20
Do you think we should go as far as just making it work that way without any options?

**Comment by Munter** [comment] 2020-07-12 13:50
It's a possibility to add this as the default behavior. IF we do, we should consider the cases where font enthusiasts have a lot of fonts across their pages, which might not be included in that many other pages. Some sort of warning threshold when a lot of font declarations are suddenly in the mix at the same time, and a way to revert to the old behavior.

An alternative is of course to keep the current behavior optimized for static pages and somehow help Gatsby and similar setups to get the correct setup. I'm unsure what we should attempt to detect in this case though. Specifically for Gatsby, we could add a PR for https://www.gatsbyjs.org/packages/gatsby-plugin-subfont/ to have it configures optimally for Gatsby. That wouldn't help other setups that use the same technique though. Of course, in the ideal world, just adding some documentation should be enough, but it never seems to be enough :)

**Comment by papandreou** [comment] 2020-07-12 22:56
> It's a possibility to add this as the default behavior. IF we do, we should consider the cases where font enthusiasts have a lot of fonts across their pages, which might not be included in that many other pages. Some sort of warning threshold when a lot of font declarations are suddenly in the mix at the same time, and a way to revert to the old behavior.

This feels like an opportunity to simplify the code and provide a reasonably footgun-less behavior. We could share the subfont CSS between all the pages, which would mitigate the extra weight of the `@font-face` declarations that aren't needed on the individual pages (at least when `--inline-css` isn't passed).

I looked at it a bit to see if it was easy to get the tests on https://github.com/Munter/subfont/pull/111 to pass, but it gets complicated by all the different modes we have. How about we kill `--subset-per-page` and adopt the suggestion here as the default behavior, then release a new major version? And the only if users can present a very convincing argument, we can try to reintroduce some of the old modes?

**Comment by papandreou** [comment] 2020-07-15 08:28
I updated #111 with an implementation that adds an `--ssr` switch. It respects the set of original `@font-face` declarations that are available on each page by not making the `__subset` variants available unless the original one was in scope.

That means that if we were to make this the default mode, users would still have that knob available if they don't want to pay the price for a certain webfont on some pages -- then they can split up their CSS in a way so that the original `@font-face` isn't in scope on those pages. That feels kinda intuitive to me.

**Comment by papandreou** [comment] 2020-07-26 15:03
@palindrom615, we just released 5.1.0, which includes a fix for this (#111). Now `subfont -i --no-fallbacks first.html second.html` should do what you originally expected. Let us know if that does the job!

**Closed** 2020-08-15 08:57 UTC
Labels: enhancement, semver-minor
