### ISSUE TITLE
How to include `font-display: swap` with subfont?

### ISSUE THREAD

**Issue by ajmalafif** [Munter/subfont#47] opened 2018-12-17 16:17 UTC
I am using Subfont with Gatsby through https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-subfont

Thanks for the awesome work, I love how things just work with subfont! I am by all means not an expert in JS, i'm using subfont and Gatsby because it's great accessible tools for beginner like myself. 

I am stuck at how do I include `@font-face { font-display:swap;}` with subfont because I tried to do it myself, but it doesn't seem to pick it up:

Repo: https://github.com/ajmalafif/gatsby-interUI/blob/master/src/components/layout.js
Example: https://gatsby-interui.netlify.com/

![2cnazc4q](https://user-images.githubusercontent.com/827167/50099913-2dc97380-025a-11e9-9f87-7badaa2f7b22.png)

### font-display though included in the code, not picked up by the browser
![veqaks4g](https://user-images.githubusercontent.com/827167/50101823-8ef34600-025e-11e9-8f85-0981a19fb3e2.png)

**Comment by papandreou** [comment] 2018-12-17 20:39
Hmm, when I clone your repo and run `gatsby build`, `font-display: swap` does get injected into the `@font-face` declaration for the subset font:

```css
      @font-face {
        font-display: swap;
        font-family: Inter UI__subset;
        font-stretch: normal;
        font-style: normal;
        font-weight: 600;
        src: url(/subfont/Inter_UI-600-7e943e72da.woff2) format('woff2'),
          url(/subfont/Inter_UI-600-c99b110d8d.woff) format('woff');
        unicode-range: U+65, U+69, U+6c, U+6e-70, U+72-74, U+76, U+79, U+20,
          U+32, U+47-49, U+55, U+61-62;
      }
```

That does not seem to be the case on https://gatsby-interui.netlify.com -- in fact it looks like (gatsby-plugin-)subfont didn't run during the build at all! Did you turn off subfont again and rebuild after reporting this issue?

Also, could you explain exactly what you expected to happen?

**Comment by ajmalafif** [comment] 2018-12-18 02:53
Hi @papandreou, thanks so much for taking a look. Really appreciate it!

I replicate what you said on office laptop, and it loads!

I actually did nothing differently for the https://gatsby-interui.netlify.com. Hmm, maybe this is an issue with Gatsby not subfont seems it works perfectly as we seen on local. I'll direct my question to Gatsby repo next then.

I think I expected it to include the code you show above with `font-display: swap`:
![gatsby_v2_interui](https://user-images.githubusercontent.com/827167/50129086-7d3b8e00-02b2-11e9-8c64-db6f1b1553ee.png)

Right now, for the netlify link it is missing somehow

**Comment by ajmalafif** [comment] 2018-12-18 05:38
Ah i think i got it why. Here's `gatsby-interUI` Netlify deploy log:
```
1:35:17 PM: Build ready to start
1:35:18 PM: build-image version: 53a2d5fe9ca22a80747972bf7a83d93509ec503c
1:35:19 PM: buildbot version: 4011bc275ed1e45f93e758dff0bce4fda2a3c46f
1:35:19 PM: Fetching cached dependencies
1:35:19 PM: Starting to download cache of 106.5MB
1:35:20 PM: Finished downloading cache in 903.325845ms
1:35:20 PM: Starting to extract cache
1:35:23 PM: Finished extracting cache in 3.529560445s
1:35:23 PM: Finished fetching cache in 4.498622009s
1:35:23 PM: Starting to prepare the repo for build
1:35:24 PM: Preparing Git Reference refs/heads/master
1:35:24 PM: Starting build script
1:35:24 PM: Installing dependencies
1:35:24 PM: Started restoring cached node version
1:35:26 PM: Finished restoring cached node version
1:35:27 PM: v8.14.0 is already installed.
1:35:28 PM: Now using node v8.14.0 (npm v6.4.1)
1:35:28 PM: Attempting ruby version 2.3.6, read from environment
1:35:29 PM: Using ruby version 2.3.6
1:35:29 PM: Using PHP version 5.6
1:35:29 PM: Started restoring cached node modules
1:35:29 PM: Finished restoring cached node modules
1:35:30 PM: Started restoring cached go cache
1:35:30 PM: Finished restoring cached go cache
1:35:30 PM: unset GOOS;
1:35:30 PM: unset GOARCH;
1:35:30 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
1:35:30 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
1:35:30 PM: go version >&2;
1:35:30 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
1:35:30 PM: go version go1.10 linux/amd64
1:35:30 PM: Installing missing commands
1:35:30 PM: Verify run directory
1:35:30 PM: Executing user command: gatsby build && subfont public -i
1:35:32 PM: success open and validate gatsby-config — 0.006 s
1:35:32 PM: success load plugins — 0.168 s
1:35:32 PM: success onPreInit — 0.216 s
1:35:32 PM: success delete html and css files from previous builds — 0.005 s
1:35:32 PM: success initialize cache — 0.006 s
1:35:32 PM: success copy gatsby files — 0.013 s
1:35:32 PM: success onPreBootstrap — 0.009 s
1:35:32 PM: success source and transform nodes — 0.019 s
1:35:32 PM: success building schema — 0.145 s
1:35:32 PM: success createPages — 0.006 s
1:35:33 PM: success createPagesStatefully — 0.029 s
1:35:33 PM: success onPreExtractQueries — 0.000 s
1:35:33 PM: success update schema — 0.066 s
1:35:33 PM: success extract queries from components — 0.039 s
1:35:33 PM: success run graphql queries — 0.030 s — 6/6 205.85 queries/second
1:35:33 PM: success write out page data — 0.004 s
1:35:33 PM: success write out redirect data — 0.000 s
1:35:33 PM: done generating icons for manifest
1:35:33 PM: success onPostBootstrap — 0.236 s
1:35:33 PM: info bootstrap finished - 3.288 s
1:35:37 PM: success Building production JavaScript and CSS bundles — 4.214 s
1:35:38 PM: success Building static HTML for pages — 0.753 s — 5/5 18.87 pages/second
1:35:42 PM:  ⚠ WARN: ENOENT: no such file or directory, open 'public/sw.js'
1:35:42 PM:          Including assets:
1:35:42 PM:              public/app-96e45d71151e54262248.js
1:35:42 PM: /bin/sh: 1: pyftsubset: not found
1:35:42 PM: Generated public/sw.js, which will precache 18 files, totaling 629902 bytes.
1:35:42 PM: info Done building in 12.466 sec
1:35:44 PM: Guessing --root from input files: file:///opt/build/repo/public
1:35:44 PM:  ✔ 0.002 secs: logEvents
1:35:44 PM:  ✔ 0.009 secs: loadAssets
1:35:45 PM:  ⚠ WARN: ENOENT: no such file or directory, open 'public/workbox-v3.6.2/packages/workbox-sw/browser.mjs'
1:35:45 PM:          Including assets:
1:35:45 PM:              public/workbox-v3.6.2/workbox-sw.js.map
1:35:45 PM:  ✔ 1.067 secs: populate
1:35:45 PM:  ✔ 0.049 secs: checkIncompatibleTypes
1:35:46 PM:  ✔ 0.025 secs: populate
1:35:46 PM: /bin/sh: 1: pyftsubset: not found
1:35:46 PM:  ℹ INFO: Local subsetting is not possible because fonttools are not installed. Falling back to only subsetting Google Fonts. Run `pip install fonttools brotli zopfli` to enable local font subsetting
1:35:46 PM:  ✔ 0.432 secs: subsetFonts
1:35:46 PM:  ✔ 0.054 secs: compressJavaScript
1:35:46 PM:  ✔ 0.009 secs: writeAssetsToDisc
1:35:46 PM: HTML/JS/CSS size increase: 341 B
1:35:46 PM: Total savings: -341 B
1:35:46 PM: Output written to file:///opt/build/repo/public/
1:35:46 PM: Caching artifacts
1:35:46 PM: Started saving node modules
1:35:46 PM: Finished saving node modules
1:35:46 PM: Started saving pip cache
1:35:46 PM: Finished saving pip cache
1:35:46 PM: Started saving emacs cask dependencies
1:35:46 PM: Finished saving emacs cask dependencies
1:35:46 PM: Started saving maven dependencies
1:35:46 PM: Finished saving maven dependencies
1:35:46 PM: Started saving boot dependencies
1:35:46 PM: Finished saving boot dependencies
1:35:46 PM: Started saving go dependencies
1:35:46 PM: Finished saving go dependencies
1:35:46 PM: Build script success
1:35:46 PM: Starting to deploy site from 'public/'
1:35:50 PM: Starting post processing
1:35:50 PM: Post processing done
1:35:50 PM: Site is live
1:36:02 PM: Finished processing build request in 43.358996602s
```

**Comment by ajmalafif** [comment] 2018-12-18 05:53
https://github.com/ajmalafif/gatsby-interUI/blob/5d4e52fbd9d3a49db55d079b896eb2706e6c0206/netlify.toml#L5

This seems to fix this issue, but have much lower Lighthouse score of 80 (it was 99 earlier!). I thought this fix would push it to 💯 haha. Thanks anyways all!

**Comment by papandreou** [comment] 2018-12-18 07:58
Hmm, looks like you've discovered a bug in subfont. It's injecting `<link rel="preload" as="font" type="font/woff2" crossorigin="anonymous" href="...">` tags for every font variant available, not only the subset ones. We should get that fixed.

**Comment by papandreou** [comment] 2018-12-19 23:47
@Munter, I started writing some test cases and got a bit confused by a comment in the code: https://github.com/assetgraph/assetgraph/blob/4abad22ebeafeedc2bd130c969f86f1361cf43fe/lib/transforms/subsetFonts.js#L845

What does that mean, exactly? Is it actually our strategy to preload all the fonts that we have found (statically) not to be in use?

I have not reproduced the exact case that happens in @ajmalafif's build, but I have made [a test case](https://github.com/assetgraph/assetgraph/blob/104f4902713ac33aea948b22f4a8ba13033a1102/test/transforms/subsetFonts.js#L3270-L3304) that gets the `new FontFace` preload fallback injected for unused variants.

Here's how it fails: https://travis-ci.org/assetgraph/assetgraph/jobs/470276155#L645-L650

Again, is this intentional?

**Comment by Munter** [comment] 2018-12-21 12:18
@ajmalafif Instead of putting the pip installation in your build script, try using a [requirements.txt](https://github.com/Munter/mntr.dk/blob/master/requirements.txt). That should hook better into the Netlify caching pipeline I think

**Comment by ajmalafif** [comment] 2018-12-21 15:11
@Munter thanks for the suggestion! Made the changes and yeah it does and deployed way faster too!

I think now the initial reported issue is addressed; which was `font-display:swap` in the code as per development. 

So I am not too sure if I should close this issue or is it okay to just continue so we can address the accidental discovery of the bug mentioned by @papandreou?

**Comment by papandreou** [comment] 2018-12-21 18:18
@ajmalafif, OK to close it, I'm already exploring the other thing. Just need a bit of feedback from @Munter to be able to proceed :)

**Closed by papandreou** 2018-12-21 18:18 UTC

**Comment by ajmalafif** [comment] 2018-12-23 09:31
Just to update those who are referring to this issue; I've since replaced the codebase and netlify preview to a specific repo and deployment here:

repo: https://github.com/ajmalafif/gatsby-interUI-subfont
site: https://gatsby-interui-subfont.netlify.com/

oh and happy holidays all! 🎄
